{% set repo_name = "scimma" %}
{% set pack_name = "client_library" %}

#{% set setup_data = load_setup_py_data() %}
#{% from setuptools_scm import get_version %}
{% set version = GIT_DESCRIBE_TAG %}

package:
  name: "{{ pack_name|lower }}"
  #version: {{ setup_data.get('version') }}
  #version: {{ get_version() }}
  version: {{ version }}

source:
  url: "https://github.com/{{ repo_name }}/{{ pack_name }}/archive/{{ version }}.tar.gz"
  sha256: "c0f87a158f6ea3cd302b13fec00b81445a6edf3e4629a8744078ad120f810f69"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - scimma = scimma.client.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - 'adc[channel=scimma]'

test:
  imports:
    - scimma
    - scimma.client
    - scimma.client.publish

about:
  home: "https://github.com/scimma/client_library"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "A client library for SCiMMA"
  doc_url: ""
  dev_url: ""
