name: Upload to Anaconda

on:
  push:
    tags:
      - 'v*'

jobs:
  Upload:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        conda install -y anaconda-client conda-build
        conda install -y setuptools setuptools_scm
    - name: Build package and update conda recipe
      run: |
        python3 setup.py sdist
        wget https://github.com/mikefarah/yq/releases/download/3.1.0/yq_linux_amd64 -O yq
        chmod +x yq
        ./yq n package.version $(python setup.py --version) > update.yaml
        conda render recipe/meta.yaml --append-file update.yaml
        ./yq n source.sha256 $(openssl sha256 dist/*.tar.gz | awk '{print $2}') > update_hash.yaml
        conda render recipe/meta.yaml --append-file update_hash.yaml
    - name: Upload to Anaconda
      env:
        CONDA_USERNAME: ${{ secrets.CONDA_USER_scimma }}
        CONDA_PASSWORD: ${{ secrets.CONDA_PW_scimma }}
      run: |
        conda config --set anaconda_upload yes
        anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
        conda build .
        anaconda logout
