name: Upload to Anaconda

on:
  push:
    tags:
      - 'v*'

jobs:
  Upload:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        conda install -y anaconda-client conda-build
        conda install -y setuptools setuptools_scm

    - name: Update recipe with version variable
      env:
        #can't read source url from recipe, so generate it here:
        NAME: 'scimma-client'
        RECIPE_PATH: 'recipe/meta.yaml'
        #VERSION: $(python setup.py --version)
        #LINE_STR: '{% set version = "v'${VERSION}'" %}'
        #SOURCE_URL: "https://pypi.io/packages/source/s/${NAME}/${NAME}-${VERSION}.tar.gz"

      run: |
        #create env vars that cannot be created above due to syntax
        VERSION=$(python setup.py --version)
        LINE_STR='{% set version = "v'${VERSION}'" %}'
        SOURCE_URL="https://pypi.io/packages/source/s/${NAME}/${NAME}-${VERSION}.tar.gz"

        #prepend version environment variable before writing files (preserves version of master)
        echo $LINE_STR | cat - $RECIPE_PATH > temp && mv temp $RECIPE_PATH
        
        #download tarball from pypi for hash generation
        pip download $SOURCE_URL --no-deps --no-binary :all:
        
        #use openssl to generate hash and yq to write updated hash to file
        wget https://github.com/mikefarah/yq/releases/download/3.1.0/yq_linux_amd64 -O yq
        chmod +x yq
        ./yq n source.sha256 $(openssl sha256 ${NAME}-${VERSION}.tar.gz | awk '{print $2}') >> update.yaml

    - name: Apply updated hash
      run: |
        #render the recipe file with the generated hash
        conda render recipe/meta.yaml --clobber-file update.yaml

    - name: Add channels 
      env:
        PACK_NAME: 'scimma'
      run: |
        conda index ./$PACK_NAME
        conda config --env --add channels $PACK_NAME
        conda config --env --add channels conda-forge

    - name: Build and upload to Anaconda
      env:
        CONDA_USERNAME: ${{ secrets.CONDA_USER_scimma }}
        CONDA_PASSWORD: ${{ secrets.CONDA_PW_scimma }}
      run: |
        conda config --set anaconda_upload yes
        anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
        conda build .
        anaconda logout
